name: nifty-nlp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8
  - pandas=2.2.0
  - numpy=1.26.3
  - scikit-learn=1.4.0
  - yfinance=0.2.36
  - pyyaml=6.0.1
  - tqdm
  - pip:
      - transformers==4.37.2
      - ta-lib==0.4.28
      - accelerate==0.26.1
      - feedparser==6.0.10
      - beautifulsoup4==4.12.3
      - schedule==1.2.1
